# Generated by Django 5.1.2 on 2024-10-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_address',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
    ]
