# Generated by Django 5.1.2 on 2024-10-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_profile_name_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profile_images/default.jpg', null=True, upload_to='images/profile_images/'),
        ),
    ]
