# Generated by Django 5.1.2 on 2024-11-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_profile_birthday_profile_location_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
