# Generated by Django 5.1.2 on 2024-11-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
