# Generated by Django 5.1.2 on 2024-11-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='Enter number', max_length=11, null=True),
        ),
    ]
